### ISSUE TITLE
User credentials interface

### ISSUE THREAD

**Issue by vinaykumars110** [guojiex/flutter_app_cse#27]
What is the current mechanism to add or modify API Key ?

**Comment by guojiex** [comment]
I am not sure about what you are asking, but i set the api key here in code:
https://github.com/guojiex/flutter_app_cse/blob/master/lib/ui/custom_search_demo_page.dart#L77

**Comment by guojiex** [comment]
get an api key according to this doc:
https://developers.google.com/custom-search/v1/introduction

**Comment by vinaykumars110** [comment]
> I am not sure about what you are asking, but i set the api key here in code:
> https://github.com/guojiex/flutter_app_cse/blob/master/lib/ui/custom_search_demo_page.dart#L77

Yes. It is embedded as static in the code. That seems difficult to update. Better to provide a handle to update using some constructor which can be directly set in main
